# Generated by Django 5.1.1 on 2024-12-10 15:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('interview', '0002_delete_interviewtask'),
        ('jobs', '0018_job_archive_after_weeks_job_archived_and_more'),
        ('targets', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('is_completed', models.BooleanField(default=False)),
                ('polymorphic_ctype', models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='polymorphic_%(app_label)s.%(class)s_set+', to='contenttypes.contenttype')),
            ],
            options={
                'abstract': False,
                'base_manager_name': 'objects',
            },
        ),
        migrations.CreateModel(
            name='InterviewTask',
            fields=[
                ('task_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='tasks.task')),
                ('interview', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tasks', to='interview.interview')),
            ],
            options={
                'abstract': False,
                'base_manager_name': 'objects',
            },
            bases=('tasks.task',),
        ),
        migrations.CreateModel(
            name='JobTask',
            fields=[
                ('task_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='tasks.task')),
                ('job', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tasks', to='jobs.job')),
            ],
            options={
                'abstract': False,
                'base_manager_name': 'objects',
            },
            bases=('tasks.task',),
        ),
        migrations.CreateModel(
            name='TargetTask',
            fields=[
                ('task_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='tasks.task')),
                ('target', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='task', to='targets.target')),
            ],
            options={
                'abstract': False,
                'base_manager_name': 'objects',
            },
            bases=('tasks.task',),
        ),
    ]
