# Generated by Django 5.1.1 on 2024-12-10 18:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0002_task_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='targettask',
            name='target',
        ),
    ]
