# Generated by Django 5.1.1 on 2024-12-10 18:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('targets', '0004_rename_current_applications_made_target_current_and_more'),
        ('tasks', '0004_task_priority'),
    ]

    operations = [
        migrations.AddField(
            model_name='targettask',
            name='target',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='task', to='targets.target'),
            preserve_default=False,
        ),
    ]
