# Generated by Django 5.1.1 on 2025-01-31 11:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0002_rename_company_job_company_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='company',
            field=models.ForeignKey(
                null=True, on_delete=django.db.models.deletion.CASCADE, to='company.company'),
        ),
    ]
