# Generated by Django 5.1.1 on 2025-08-05 11:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("jobs", "0003_job_company"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="job",
            name="company",
        ),
    ]
