version: 2

build:
  os: ubuntu-24.04
  tools:
    python: "3.11"
  jobs:
    pre_create_environment:
      # Set up settings directory
      - mkdir -p apptrack/apptrack

      # Add SECRET_KEY from environment variable
      - echo "SECRET_KEY = '${DJANGO_SECRET_KEY}'" > apptrack/apptrack/settings.py

      # Populate settings.py with test settings
      - cat test_settings.txt >> apptrack/apptrack/settings.py

      - python -m pip install -r requirements.txt

sphinx:
  configuration: docs/source/conf.py
