version: 2

build:
  os: ubuntu-22.04
  tools:
    python: "3.11"
  commands: []

python:
  install:
    - method: pip
      path: .

sphinx:
  builder: "html"
  configuration: ""

documentation_type: "sphinx"
