# Generated by Django 5.1.1 on 2024-12-10 15:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0006_remove_profile_streak_remove_profile_target_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Streak',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('current_streak_start', models.DateTimeField(blank=True, null=True)),
                ('current_streak', models.IntegerField(blank=True, default=0, null=True)),
                ('longest_streak_start', models.DateTimeField(blank=True, null=True)),
                ('longest_streak_end', models.DateTimeField(blank=True, null=True)),
                ('longest_streak', models.IntegerField(blank=True, default=0, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Target',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('target_applications_made', models.IntegerField(default=0)),
                ('current_applications_made', models.IntegerField(default=0)),
                ('total_targets_met', models.IntegerField(default=0)),
                ('last_reset', models.DateTimeField(auto_now=True)),
                ('profile', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='target', to='accounts.profile')),
                ('streak', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='target', to='targets.streak')),
            ],
        ),
    ]
