# Generated by Django 5.1.1 on 2024-12-10 15:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('targets', '0002_alter_streak_current_streak_start'),
    ]

    operations = [
        migrations.AlterField(
            model_name='target',
            name='streak',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='target', to='targets.streak'),
        ),
    ]
