# Generated by Django 5.1.1 on 2025-01-30 16:13

import django_ckeditor_5.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BlogPost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('content', django_ckeditor_5.fields.CKEditor5Field(verbose_name='text')),
                ('summary', models.TextField()),
                ('published', models.DateTimeField()),
            ],
            options={
                'ordering': ['-published'],
            },
        ),
    ]
