# Generated by Django 5.1.1 on 2024-10-09 16:14

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Columns',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('position', models.PositiveIntegerField()),
            ],
            options={
                'ordering': ['position'],
            },
        ),
        migrations.CreateModel(
            name='Boards',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=255, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('columns', models.ManyToManyField(to='jobs.columns')),
            ],
        ),
        migrations.CreateModel(
            name='Jobs',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('url', models.URLField(blank=True, null=True)),
                ('source', models.CharField(blank=True, choices=[('WW', 'Web'), ('HH', 'Headhunter'), ('NP', 'Newspaper'), ('CW', 'Company Website'), ('RF', 'Referral'), ('JB', 'Job Board'), ('RA', 'Recruitment Agency'), ('SM', 'Social Media'), ('CF', 'Career Fair'), ('IP', 'Internal Posting'), ('FP', 'Freelance Platform'), ('UC', 'University Career Services'), ('NE', 'Networking Event'), ('PA', 'Professional Association'), ('GP', 'Government Job Portal'), ('CO', 'Cold Outreach'), ('JN', 'Job Newsletter'), ('FN', 'Freelancer Network')], max_length=2, null=True)),
                ('job_title', models.CharField(blank=True, max_length=100, null=True)),
                ('job_function', models.CharField(blank=True, choices=[('AC', 'Accounting'), ('AD', 'Advertising'), ('AE', 'Aerospace Engineering'), ('AG', 'Agriculture'), ('AR', 'Architecture'), ('AU', 'Automotive Engineering'), ('AV', 'Aviation'), ('BA', 'Banking'), ('BI', 'Biotechnology'), ('BM', 'Broadcast Media'), ('BD', 'Business Development'), ('BO', 'Business Operations'), ('CE', 'Chemical Engineering'), ('CO', 'Computer Engineering'), ('CM', 'Construction Management'), ('CN', 'Consulting'), ('CS', 'Customer Service'), ('DS', 'Data Science'), ('DE', 'Design'), ('ED', 'Education'), ('EE', 'Electrical Engineering'), ('EN', 'Energy'), ('EG', 'Engineering'), ('ET', 'Entertainment'), ('ES', 'Environmental Science'), ('FI', 'Finance'), ('FS', 'Food Services'), ('GO', 'Government'), ('HE', 'Healthcare'), ('HR', 'Human Resources'), ('IT', 'Information Technology'), ('IN', 'Insurance'), ('IB', 'Investment Banking'), ('LE', 'Legal'), ('LO', 'Logistics'), ('MF', 'Manufacturing'), ('MK', 'Marketing'), ('MD', 'Media'), ('ME', 'Medical Devices'), ('MI', 'Mining'), ('NP', 'Non-profit'), ('PH', 'Pharmaceuticals'), ('PR', 'Public Relations'), ('PM', 'Project Management'), ('RE', 'Real Estate'), ('RC', 'Recruiting'), ('RT', 'Retail'), ('SA', 'Sales'), ('SP', 'Sports'), ('SC', 'Supply Chain'), ('TS', 'Technical Support'), ('TC', 'Telecommunications'), ('TR', 'Transportation'), ('TT', 'Travel & Tourism'), ('UT', 'Utilities'), ('VC', 'Venture Capital'), ('WH', 'Wholesale'), ('OT', 'Other')], max_length=2, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('company_name', models.CharField(blank=True, max_length=100, null=True)),
                ('is_recruiter', models.BooleanField(blank=True, default=False, null=True)),
                ('location_policy', models.CharField(blank=True, choices=[('UK', 'Unknown'), ('HY', 'Hybrid'), ('ON', 'On-Site'), ('RE', 'Remote'), ('FL', 'Flexible')], max_length=100, null=True)),
                ('work_contract', models.CharField(blank=True, choices=[('UK', 'Unknown'), ('FT', 'Fulltime'), ('PT', 'Parttime'), ('CO', 'Contract'), ('SE', 'Secondment')], max_length=100, null=True)),
                ('min_pay', models.IntegerField(blank=True, null=True)),
                ('max_pay', models.IntegerField(blank=True, null=True)),
                ('pay_rate', models.CharField(blank=True, choices=[('UK', 'Unknown'), ('HR', 'Hourly'), ('DY', 'Daily'), ('WK', 'Weekly'), ('MO', 'Monthly'), ('YR', 'Yearly')], max_length=2, null=True)),
                ('currency', models.CharField(blank=True, choices=[('XUA', 'ADB Unit of Account'), ('AFN', 'Afghani'), ('DZD', 'Algerian Dinar'), ('ARS', 'Argentine Peso'), ('AMD', 'Armenian Dram'), ('AWG', 'Aruban Florin'), ('AUD', 'Australian Dollar'), ('AZN', 'Azerbaijan Manat'), ('BSD', 'Bahamian Dollar'), ('BHD', 'Bahraini Dinar'), ('THB', 'Baht'), ('PAB', 'Balboa'), ('BBD', 'Barbados Dollar'), ('BYN', 'Belarusian Ruble'), ('BZD', 'Belize Dollar'), ('BMD', 'Bermudian Dollar'), ('BOB', 'Boliviano'), ('VED', 'Bolívar Soberano'), ('VES', 'Bolívar Soberano'), ('XBA', 'Bond Markets Unit European Composite Unit (EURCO)'), ('XBB', 'Bond Markets Unit European Monetary Unit (E.M.U.-6)'), ('XBD', 'Bond Markets Unit European Unit of Account 17 (E.U.A.-17)'), ('XBC', 'Bond Markets Unit European Unit of Account 9 (E.U.A.-9)'), ('BRL', 'Brazilian Real'), ('BND', 'Brunei Dollar'), ('BGN', 'Bulgarian Lev'), ('BIF', 'Burundi Franc'), ('XOF', 'CFA Franc BCEAO'), ('XAF', 'CFA Franc BEAC'), ('XPF', 'CFP Franc'), ('CVE', 'Cabo Verde Escudo'), ('CAD', 'Canadian Dollar'), ('KYD', 'Cayman Islands Dollar'), ('CLP', 'Chilean Peso'), ('XTS', 'Codes specifically reserved for testing purposes'), ('COP', 'Colombian Peso'), ('KMF', 'Comorian Franc'), ('CDF', 'Congolese Franc'), ('BAM', 'Convertible Mark'), ('NIO', 'Cordoba Oro'), ('CRC', 'Costa Rican Colon'), ('CUP', 'Cuban Peso'), ('CZK', 'Czech Koruna'), ('GMD', 'Dalasi'), ('DKK', 'Danish Krone'), ('MKD', 'Denar'), ('DJF', 'Djibouti Franc'), ('STN', 'Dobra'), ('DOP', 'Dominican Peso'), ('VND', 'Dong'), ('XCD', 'East Caribbean Dollar'), ('EGP', 'Egyptian Pound'), ('SVC', 'El Salvador Colon'), ('ETB', 'Ethiopian Birr'), ('EUR', 'Euro'), ('FKP', 'Falkland Islands Pound'), ('FJD', 'Fiji Dollar'), ('HUF', 'Forint'), ('GHS', 'Ghana Cedi'), ('GIP', 'Gibraltar Pound'), ('XAU', 'Gold'), ('HTG', 'Gourde'), ('PYG', 'Guarani'), ('GNF', 'Guinean Franc'), ('GYD', 'Guyana Dollar'), ('HKD', 'Hong Kong Dollar'), ('UAH', 'Hryvnia'), ('ISK', 'Iceland Krona'), ('INR', 'Indian Rupee'), ('IRR', 'Iranian Rial'), ('IQD', 'Iraqi Dinar'), ('JMD', 'Jamaican Dollar'), ('JOD', 'Jordanian Dinar'), ('KES', 'Kenyan Shilling'), ('PGK', 'Kina'), ('HRK', 'Kuna'), ('KWD', 'Kuwaiti Dinar'), ('AOA', 'Kwanza'), ('MMK', 'Kyat'), ('LAK', 'Lao Kip'), ('GEL', 'Lari'), ('LBP', 'Lebanese Pound'), ('ALL', 'Lek'), ('HNL', 'Lempira'), ('SLE', 'Leone'), ('SLL', 'Leone'), ('LRD', 'Liberian Dollar'), ('LYD', 'Libyan Dinar'), ('SZL', 'Lilangeni'), ('LSL', 'Loti'), ('MGA', 'Malagasy Ariary'), ('MWK', 'Malawi Kwacha'), ('MYR', 'Malaysian Ringgit'), ('MUR', 'Mauritius Rupee'), ('MXN', 'Mexican Peso'), ('MXV', 'Mexican Unidad de Inversion (UDI)'), ('MDL', 'Moldovan Leu'), ('MAD', 'Moroccan Dirham'), ('MZN', 'Mozambique Metical'), ('BOV', 'Mvdol'), ('NGN', 'Naira'), ('ERN', 'Nakfa'), ('NAD', 'Namibia Dollar'), ('NPR', 'Nepalese Rupee'), ('ANG', 'Netherlands Antillean Guilder'), ('ILS', 'New Israeli Sheqel'), ('TWD', 'New Taiwan Dollar'), ('NZD', 'New Zealand Dollar'), ('BTN', 'Ngultrum'), ('KPW', 'North Korean Won'), ('NOK', 'Norwegian Krone'), ('MRU', 'Ouguiya'), ('PKR', 'Pakistan Rupee'), ('XPD', 'Palladium'), ('MOP', 'Pataca'), ('TOP', 'Pa’anga'), ('CUC', 'Peso Convertible'), ('UYU', 'Peso Uruguayo'), ('PHP', 'Philippine Peso'), ('XPT', 'Platinum'), ('GBP', 'Pound Sterling'), ('BWP', 'Pula'), ('QAR', 'Qatari Rial'), ('GTQ', 'Quetzal'), ('ZAR', 'Rand'), ('OMR', 'Rial Omani'), ('KHR', 'Riel'), ('RON', 'Romanian Leu'), ('MVR', 'Rufiyaa'), ('IDR', 'Rupiah'), ('RUB', 'Russian Ruble'), ('RWF', 'Rwanda Franc'), ('XDR', 'SDR (Special Drawing Right)'), ('SHP', 'Saint Helena Pound'), ('SAR', 'Saudi Riyal'), ('RSD', 'Serbian Dinar'), ('SCR', 'Seychelles Rupee'), ('XAG', 'Silver'), ('SGD', 'Singapore Dollar'), ('PEN', 'Sol'), ('SBD', 'Solomon Islands Dollar'), ('KGS', 'Som'), ('SOS', 'Somali Shilling'), ('TJS', 'Somoni'), ('SSP', 'South Sudanese Pound'), ('LKR', 'Sri Lanka Rupee'), ('XSU', 'Sucre'), ('SDG', 'Sudanese Pound'), ('SRD', 'Surinam Dollar'), ('SEK', 'Swedish Krona'), ('CHF', 'Swiss Franc'), ('SYP', 'Syrian Pound'), ('BDT', 'Taka'), ('WST', 'Tala'), ('TZS', 'Tanzanian Shilling'), ('KZT', 'Tenge'), ('XXX', 'The codes assigned for transactions where no currency is involved'), ('TTD', 'Trinidad and Tobago Dollar'), ('MNT', 'Tugrik'), ('TND', 'Tunisian Dinar'), ('TRY', 'Turkish Lira'), ('TMT', 'Turkmenistan New Manat'), ('AED', 'UAE Dirham'), ('USD', 'US Dollar'), ('USN', 'US Dollar (Next day)'), ('UGX', 'Uganda Shilling'), ('UYW', 'Unidad Previsional'), ('CLF', 'Unidad de Fomento'), ('COU', 'Unidad de Valor Real'), ('UYI', 'Uruguay Peso en Unidades Indexadas (UI)'), ('UZS', 'Uzbekistan Sum'), ('VUV', 'Vatu'), ('CHE', 'WIR Euro'), ('CHW', 'WIR Franc'), ('KRW', 'Won'), ('YER', 'Yemeni Rial'), ('JPY', 'Yen'), ('CNY', 'Yuan Renminbi'), ('ZMW', 'Zambian Kwacha'), ('ZWL', 'Zimbabwe Dollar'), ('PLN', 'Zloty')], max_length=3, null=True)),
                ('note', models.TextField(blank=True, null=True)),
                ('status', models.CharField(choices=[('AP', 'applied'), ('RE', 'rejected'), ('SL', 'shortlisted'), ('IN', 'interview'), ('OF', 'offer'), ('OP', 'open'), ('CL', 'closed')], default='OP', max_length=2)),
                ('applied', models.BooleanField(blank=True, null=True)),
                ('column', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='jobs', to='jobs.columns')),
                ('location', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.locations')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
