# Generated by Django 5.1.1 on 2024-10-01 13:50

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('industry', models.CharField(max_length=100)),
                ('is_recruiter', models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name='Jobs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.URLField(blank=True)),
                ('title', models.CharField(max_length=100)),
                ('source', models.CharField(choices=[('web', 'web'), ('headhunter', 'headhunter'), ('newspaper', 'newspaper')], max_length=100)),
                ('description', models.TextField(blank=True)),
                ('location', models.CharField(max_length=100)),
                ('location_policy', models.CharField(choices=[('unknown', 'unknown'), ('hybrid', 'hybrid'), ('onsite', 'onsite'), ('remote', 'remote'), ('flexible', 'flexible')], max_length=100)),
                ('status', models.CharField(choices=[('archived', 'archived'), ('applied', 'applied'), ('rejected', 'rejected'), ('shortlisted', 'shortlisted'), ('interview', 'interview'), ('offer', 'offer'), ('open', 'open'), ('closed', 'closed')], default='unknown', max_length=100)),
                ('work_contract', models.CharField(choices=[('unknown', 'unknown'), ('fulltime', 'fulltime'), ('parttime', 'parttime'), ('contract', 'contract'), ('secondment', 'secondment')], default='unknown', max_length=100)),
                ('pay_rate', models.CharField(choices=[('unknown', 'unknown'), ('hourly', 'hourly'), ('daily', 'daily'), ('weekly', 'weekly'), ('monthly', 'monthly'), ('yearly', 'yearly')], default='unknown', max_length=100)),
                ('note', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='jobs.company')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
