# Generated by Django 5.1.1 on 2024-10-03 15:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jobs',
            name='currency',
            field=models.CharField(blank=True, max_length=3, null=True),
        ),
        migrations.AlterField(
            model_name='jobs',
            name='pay_rate',
            field=models.CharField(blank=True, choices=[('UK', 'Unknown'), ('HR', 'Hourly'), ('DY', 'Daily'), ('WK', 'Weekly'), ('MO', 'Monthly'), ('YR', 'Yearly')], max_length=2, null=True),
        ),
        migrations.AlterField(
            model_name='jobs',
            name='status',
            field=models.CharField(choices=[('AP', 'applied'), ('RE', 'rejected'), ('SL', 'shortlisted'), ('IN', 'interview'), ('OF', 'offer'), ('OP', 'open'), ('CL', 'closed')], default='OP', max_length=2),
        ),
    ]
