# Generated by Django 5.1.1 on 2025-01-16 14:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
        ('jobs', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='job',
            old_name='auto_archive',
            new_name='has_been_archived',
        ),
        migrations.RemoveField(
            model_name='job',
            name='archive_after_weeks',
        ),
        migrations.CreateModel(
            name='Settings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('auto_archive', models.BooleanField(blank=True, default=True, null=True)),
                ('archive_after_weeks', models.IntegerField(blank=True, default=2, null=True)),
                ('profile', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='job_settings', to='accounts.profile')),
            ],
        ),
    ]
