# Generated by Django 5.1.1 on 2024-10-05 08:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='boards',
            name='columns',
            field=models.ManyToManyField(to='jobs.columns'),
        ),
    ]
