# Generated by Django 5.1.1 on 2024-10-08 15:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobs',
            name='applied',
            field=models.BooleanField(blank=True, null=True),
        ),
    ]
