# Generated by Django 5.1.1 on 2024-12-17 10:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('jobs', '0001_initial'),
        ('target', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='targettask',
            name='target',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='task', to='target.target'),
        ),
    ]
