# Generated by Django 5.1.1 on 2024-10-23 04:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0002_alter_jobs_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jobs',
            name='id',
            field=models.BigAutoField(primary_key=True, serialize=False),
        ),
    ]
