# Generated by Django 5.1.1 on 2024-11-28 11:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0002_remove_jobs_location_jobs_country_jobs_region_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='jobs',
            old_name='company_name',
            new_name='company',
        ),
    ]
