# Generated by Django 5.1.1 on 2024-10-05 09:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0004_alter_jobs_column'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jobs',
            name='column',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='jobs', to='jobs.columns'),
        ),
    ]
