# Generated by Django 5.1.1 on 2024-11-28 16:08

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0005_alter_jobs_country'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Boards',
            new_name='Board',
        ),
        migrations.RenameModel(
            old_name='Jobs',
            new_name='Job',
        ),
        migrations.CreateModel(
            name='Column',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('position', models.PositiveIntegerField()),
                ('board', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='columns', to='jobs.board')),
            ],
            options={
                'ordering': ['position'],
                'unique_together': {('board', 'name', 'position')},
            },
        ),
        migrations.AlterField(
            model_name='job',
            name='column',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='column', to='jobs.column'),
        ),
        migrations.DeleteModel(
            name='Columns',
        ),
    ]
