# Generated by Django 5.1.1 on 2024-10-03 10:07

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0005_alter_jobs_pay_rate_alter_jobs_status_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameField(
            model_name='jobs',
            old_name='title',
            new_name='job_title',
        ),
        migrations.AddField(
            model_name='companies',
            name='created_by',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='created_companies', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='companies',
            name='linkedin',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='companies',
            name='updated_by',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='updated_companies', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='companies',
            name='website',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='jobs',
            name='job_function',
            field=models.CharField(blank=True, choices=[('acct', 'Accounting'), ('advt', 'Advertising'), ('aero_eng', 'Aerospace Engineering'), ('agri', 'Agriculture'), ('arch', 'Architecture'), ('auto_eng', 'Automotive Engineering'), ('aviation', 'Aviation'), ('banking', 'Banking'), ('biotech', 'Biotechnology'), ('broadcast', 'Broadcast Media'), ('bus_dev', 'Business Development'), ('bus_ops', 'Business Operations'), ('chem_eng', 'Chemical Engineering'), ('comp_eng', 'Computer Engineering'), ('constr_mgmt', 'Construction Management'), ('consulting', 'Consulting'), ('cust_serv', 'Customer Service'), ('data_sci', 'Data Science'), ('design', 'Design'), ('edu', 'Education'), ('elec_eng', 'Electrical Engineering'), ('energy', 'Energy'), ('eng', 'Engineering'), ('ent', 'Entertainment'), ('env_sci', 'Environmental Science'), ('fin', 'Finance'), ('food_serv', 'Food Services'), ('govt', 'Government'), ('health', 'Healthcare'), ('hr', 'Human Resources'), ('it', 'Information Technology'), ('insurance', 'Insurance'), ('inv_banking', 'Investment Banking'), ('legal', 'Legal'), ('logistics', 'Logistics'), ('mfg', 'Manufacturing'), ('marketing', 'Marketing'), ('media', 'Media'), ('med_dev', 'Medical Devices'), ('mining', 'Mining'), ('non_profit', 'Non-profit'), ('pharma', 'Pharmaceuticals'), ('pr', 'Public Relations'), ('project_mgmt', 'Project Management'), ('real_estate', 'Real Estate'), ('recruiting', 'Recruiting'), ('retail', 'Retail'), ('sales', 'Sales'), ('sports', 'Sports'), ('supply_chain', 'Supply Chain'), ('tech_support', 'Technical Support'), ('telecom', 'Telecommunications'), ('transport', 'Transportation'), ('travel', 'Travel & Tourism'), ('utilities', 'Utilities'), ('venture_cap', 'Venture Capital'), ('wholesale', 'Wholesale'), ('other', 'Other')], max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='companies',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='companies',
            name='industry',
            field=models.CharField(blank=True, choices=[('acct', 'Accounting'), ('advt', 'Advertising'), ('aero', 'Aerospace'), ('agri', 'Agriculture'), ('apparel', 'Apparel & Fashion'), ('arch', 'Architecture'), ('auto', 'Automotive'), ('aviation', 'Aviation'), ('bank', 'Banking'), ('bio', 'Biotechnology'), ('broadcast', 'Broadcast Media'), ('build_mat', 'Building Materials'), ('bus_serv', 'Business Services'), ('chem', 'Chemicals'), ('comp_sftw', 'Computer Software'), ('constr', 'Construction'), ('cons_goods', 'Consumer Goods'), ('cons_serv', 'Consumer Services'), ('defense', 'Defense & Space'), ('design', 'Design'), ('edu', 'Education'), ('elec', 'Electronics'), ('energy', 'Energy'), ('eng', 'Engineering'), ('ent', 'Entertainment'), ('env_serv', 'Environmental Services'), ('fin_serv', 'Financial Services'), ('food_bev', 'Food & Beverage'), ('govt', 'Government'), ('health', 'Healthcare'), ('hosp', 'Hospitality'), ('hr', 'Human Resources'), ('it', 'Information Technology'), ('insurance', 'Insurance'), ('inv_bank', 'Investment Banking'), ('legal', 'Legal Services'), ('logistics', 'Logistics & Supply Chain'), ('mfg', 'Manufacturing'), ('mktg', 'Marketing'), ('media', 'Media'), ('med_dev', 'Medical Devices'), ('mining', 'Mining'), ('non_profit', 'Non-profit'), ('pharma', 'Pharmaceuticals'), ('pr', 'Public Relations'), ('publishing', 'Publishing'), ('real_est', 'Real Estate'), ('recruiting', 'Recruiting'), ('retail', 'Retail'), ('sports', 'Sports'), ('tech', 'Technology'), ('telecom', 'Telecommunications'), ('transp', 'Transportation'), ('travel', 'Travel & Tourism'), ('utilities', 'Utilities'), ('vc', 'Venture Capital'), ('wholesale', 'Wholesale'), ('other', 'Other')], max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='companies',
            name='is_recruiter',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='jobs',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='jobs',
            name='location_policy',
            field=models.CharField(blank=True, choices=[('unknown', 'unknown'), ('hybrid', 'hybrid'), ('onsite', 'onsite'), ('remote', 'remote'), ('flexible', 'flexible')], max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='jobs',
            name='note',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='jobs',
            name='pay_rate',
            field=models.CharField(blank=True, choices=[('unknown', 'unknown'), ('hourly', 'hourly'), ('daily', 'daily'), ('weekly', 'weekly'), ('monthly', 'monthly'), ('yearly', 'yearly')], max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='jobs',
            name='status',
            field=models.CharField(blank=True, choices=[('archived', 'archived'), ('applied', 'applied'), ('rejected', 'rejected'), ('shortlisted', 'shortlisted'), ('interview', 'interview'), ('offer', 'offer'), ('open', 'open'), ('closed', 'closed')], max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='jobs',
            name='url',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='jobs',
            name='work_contract',
            field=models.CharField(blank=True, choices=[('unknown', 'unknown'), ('fulltime', 'fulltime'), ('parttime', 'parttime'), ('contract', 'contract'), ('secondment', 'secondment')], max_length=100, null=True),
        ),
    ]
