# Generated by Django 5.1.1 on 2024-10-05 09:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0005_alter_jobs_column'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobs',
            name='position',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
