# Generated by Django 5.1.1 on 2024-10-05 10:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0006_jobs_position'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='jobs',
            name='position',
        ),
    ]
