# Generated by Django 5.1.1 on 2024-10-03 10:45

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0007_remove_jobs_note_remove_jobs_status_remove_jobs_user_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='jobs',
            name='users_with_access',
            field=models.ManyToManyField(blank=True, related_name='users_with_access', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='userjobsdetails',
            name='job',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='jobs.jobs'),
        ),
    ]
