# Generated by Django 5.1.1 on 2024-10-05 10:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0007_remove_jobs_position'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobs',
            name='position',
            field=models.PositiveIntegerField(default=1),
        ),
    ]
