# Generated by Django 5.1.1 on 2024-11-28 16:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0007_alter_board_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='board',
            name='name',
            field=models.CharField(blank=True, default='My Job Board', max_length=255, null=True),
        ),
    ]
