# Generated by Django 5.1.1 on 2024-10-03 11:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0008_jobs_users_with_access_alter_userjobsdetails_job'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userjobsdetails',
            name='status',
            field=models.CharField(blank=True, choices=[('arc', 'archived'), ('app', 'applied'), ('rej', 'rejected'), ('sli', 'shortlisted'), ('int', 'interview'), ('off', 'offer'), ('ope', 'open'), ('clo', 'closed')], max_length=3, null=True),
        ),
    ]
