# Generated by Django 5.1.1 on 2024-11-30 14:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0009_job_created_job_updated'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job',
            name='status',
            field=models.CharField(choices=[('OP', 'Open'), ('AP', 'Applied'), ('RE', 'Rejected'), ('SL', 'Shortlisted'), ('IN', 'Interview'), ('OF', 'Offer'), ('CL', 'Closed')], default='OP', max_length=2),
        ),
        migrations.AlterField(
            model_name='job',
            name='updated',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
