# Generated by Django 5.1.1 on 2024-10-03 12:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0010_remove_jobs_company_remove_jobs_location_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userjobsdetails',
            name='job',
        ),
    ]
