# Generated by Django 5.1.1 on 2024-12-03 13:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_task'),
        ('jobs', '0010_alter_job_status_alter_job_updated'),
    ]

    operations = [
        migrations.CreateModel(
            name='JobTask',
            fields=[
                ('task_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='core.task')),
                ('job', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tasks', to='jobs.job')),
            ],
            bases=('core.task',),
        ),
    ]
