# Generated by Django 5.1.1 on 2024-10-03 12:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0011_remove_userjobsdetails_job'),
    ]

    operations = [
        migrations.AddField(
            model_name='userjobsdetails',
            name='job',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='jobs.jobs'),
        ),
    ]
