# Generated by Django 5.1.1 on 2024-12-05 14:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0011_jobtask'),
    ]

    operations = [
        migrations.DeleteModel(
            name='JobTask',
        ),
    ]
