# Generated by Django 5.1.1 on 2024-12-12 14:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0011_feedback_reminder_task_jobfunction_locationpolicy_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='date_offered_set',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='job',
            name='offered',
            field=models.BooleanField(blank=True, null=True),
        ),
    ]
