# Generated by Django 5.1.1 on 2024-10-03 13:12

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0013_jobs_company'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='companies',
            name='size',
            field=models.CharField(blank=True, choices=[('uk', 'unknown'), ('su', 'startup'), ('es', 'established'), ('en', 'enterprise')], default='uk', max_length=2, null=True),
        ),
        migrations.AlterField(
            model_name='jobs',
            name='source',
            field=models.CharField(choices=[('web', 'Web'), ('hh', 'Headhunter'), ('np', 'Newspaper'), ('cw', 'Company Website'), ('rf', 'Referral'), ('jb', 'Job Board'), ('ra', 'Recruitment Agency'), ('sm', 'Social Media'), ('cf', 'Career Fair'), ('ip', 'Internal Posting'), ('fp', 'Freelance Platform'), ('uc', 'University Career Services'), ('ne', 'Networking Event'), ('pa', 'Professional Association'), ('gp', 'Government Job Portal'), ('co', 'Cold Outreach'), ('jn', 'Job Newsletter'), ('fn', 'Freelancer Network')], max_length=100),
        ),
        migrations.AddConstraint(
            model_name='companies',
            constraint=models.UniqueConstraint(fields=('name', 'website'), name='unique_company_name'),
        ),
        migrations.AddConstraint(
            model_name='companies',
            constraint=models.UniqueConstraint(fields=('name', 'linkedin'), name='unique_company_linkedin'),
        ),
        migrations.AddConstraint(
            model_name='companies',
            constraint=models.UniqueConstraint(fields=('name', 'industry'), name='unique_name_industry'),
        ),
        migrations.AddConstraint(
            model_name='companies',
            constraint=models.UniqueConstraint(fields=('website', 'linkedin'), name='unique_website_linkedin'),
        ),
    ]
