# Generated by Django 5.1.1 on 2024-12-13 11:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0013_jobfunction_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='interview',
            name='round',
            field=models.IntegerField(default=1),
        ),
    ]
