# Generated by Django 5.1.1 on 2024-12-08 13:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0013_alter_board_user'),
    ]

    operations = [
        migrations.RenameField(
            model_name='job',
            old_name='town',
            new_name='city',
        ),
    ]
