# Generated by Django 5.1.1 on 2024-10-03 13:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0014_companies_size_alter_jobs_source_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='companies',
            name='name',
            field=models.CharField(max_length=255),
        ),
    ]
