# Generated by Django 5.1.1 on 2024-12-09 15:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0016_jobfunction_locationpolicy_payrate_workcontract_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='date_applied',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='job',
            name='date_interviewed_set',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='job',
            name='interviewed',
            field=models.BooleanField(blank=True, null=True),
        ),
    ]
