# Generated by Django 5.1.1 on 2024-12-10 10:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0017_job_date_applied_job_date_interviewed_set_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='archive_after_weeks',
            field=models.IntegerField(blank=True, default=2, null=True),
        ),
        migrations.AddField(
            model_name='job',
            name='archived',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
        migrations.AddField(
            model_name='job',
            name='auto_archive',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
    ]
