# Generated by Django 5.1.1 on 2025-08-05 11:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("tasks", "0001_initial"),
    ]

    operations = [
        migrations.DeleteModel(
            name="InterviewTask",
        ),
        migrations.DeleteModel(
            name="JobTask",
        ),
    ]
