# Generated by Django 5.1.1 on 2025-08-05 11:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("tasks", "0002_remove_jobtask_job_remove_jobtask_task_ptr_and_more"),
    ]

    operations = [
        migrations.DeleteModel(
            name="Task",
        ),
    ]
