# Generated by Django 5.1.1 on 2025-08-05 11:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("company", "0001_initial"),
        ("jobs", "0004_remove_job_company"),
    ]

    operations = [
        migrations.DeleteModel(
            name="Company",
        ),
    ]
