# Generated by Django 5.1.1 on 2024-10-09 09:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_customuser_email_verified'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='last_verification_email_sent',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
