# Generated by Django 5.1.1 on 2024-10-09 12:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_customuser_last_verification_email_sent'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='email_comms_opt_in',
            field=models.BooleanField(default=False),
        ),
    ]
