# Generated by Django 5.1.1 on 2024-12-10 10:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_alter_streak_current_streak_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='current_applications_made',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
