# Generated by Django 5.1.1 on 2024-12-10 15:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_alter_profile_current_applications_made'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='streak',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='target',
        ),
        migrations.DeleteModel(
            name='Streak',
        ),
        migrations.DeleteModel(
            name='Target',
        ),
    ]
