# Generated by Django 5.1.1 on 2024-12-11 17:37

import django.db.models.deletion
import django.db.models.query
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_streak_target'),
    ]

    operations = [
        migrations.RenameField(
            model_name='target',
            old_name='daily_target',
            new_name='amount',
        ),
        migrations.AlterField(
            model_name='target',
            name='streak',
            field=models.ForeignKey(default=django.db.models.query.QuerySet.create, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='target', to='accounts.streak'),
        ),
    ]
