# Generated by Django 5.1.1 on 2024-12-12 14:44

import django.db.models.deletion
import django.db.models.query
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_rename_daily_target_target_amount_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='target',
            name='amount',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='target',
            name='current',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='target',
            name='streak',
            field=models.ForeignKey(default=django.db.models.query.QuerySet.create, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='target', to='accounts.streak'),
        ),
    ]
