# Generated by Django 5.1.1 on 2024-12-13 10:25

import django.db.models.deletion
import django.db.models.query
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0009_alter_target_amount_alter_target_current_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='target',
            name='streak',
            field=models.ForeignKey(default=django.db.models.query.QuerySet.create, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='target', to='accounts.streak'),
        ),
    ]
