# Generated by Django 5.1.1 on 2024-12-16 13:08

import django.db.models.deletion
import django.db.models.query
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0020_alter_target_streak'),
    ]

    operations = [
        migrations.AlterField(
            model_name='target',
            name='streak',
            field=models.ForeignKey(default=django.db.models.query.QuerySet.create, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='target', to='accounts.streak', unique=True),
        ),
    ]
