# Generated by Django 5.1.1 on 2025-08-05 11:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("interviews", "0001_initial"),
    ]

    operations = [
        migrations.DeleteModel(
            name="Interview",
        ),
    ]
