# Generated by Django 5.1.1 on 2024-12-13 10:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_country_currency_delete_locations'),
    ]

    operations = [
        migrations.RenameField(
            model_name='country',
            old_name='iso2',
            new_name='alpha_2',
        ),
        migrations.RenameField(
            model_name='currency',
            old_name='iso3',
            new_name='alpha_3',
        ),
    ]
