# Generated by Django 5.1.1 on 2024-12-06 15:00

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_task'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Reminder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reminder_offset', models.IntegerField(default=1)),
                ('reminder_unit', models.CharField(choices=[('d', 'Days'), ('h', 'Hours'), ('m', 'Minutes')], max_length=1)),
                ('emailed', models.BooleanField(blank=True, default=False)),
                ('message', models.TextField()),
                ('read', models.BooleanField(default=False)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.DeleteModel(
            name='Locations',
        ),
    ]
