# Generated by Django 5.1.1 on 2024-12-03 15:22

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_task'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Alert',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('alert_before', models.IntegerField(default=1)),
                ('alert_before_unit', models.CharField(choices=[('d', 'Days'), ('h', 'Hours'), ('m', 'Minutes')], max_length=1)),
                ('alert_type', models.CharField(max_length=20)),
                ('alert_via_email', models.BooleanField(default=False)),
                ('alert_via_push', models.BooleanField(default=False)),
                ('emailed', models.BooleanField(blank=True, default=False)),
                ('persistent', models.BooleanField(default=False)),
                ('persistent_until_read', models.BooleanField(default=False)),
                ('message', models.TextField()),
                ('read', models.BooleanField(default=False)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
