# Generated by Django 5.1.1 on 2024-12-04 16:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_alert'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='alert',
            name='alert_type',
        ),
        migrations.RemoveField(
            model_name='alert',
            name='alert_via_email',
        ),
        migrations.RemoveField(
            model_name='alert',
            name='alert_via_push',
        ),
        migrations.RemoveField(
            model_name='alert',
            name='persistent',
        ),
        migrations.RemoveField(
            model_name='alert',
            name='persistent_until_read',
        ),
    ]
