# Generated by Django 5.1.1 on 2024-12-13 11:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_rename_iso2_country_alpha_2_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='currency',
            name='symbol',
        ),
    ]
