# Generated by Django 5.1.1 on 2024-12-06 15:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_reminder_delete_locations'),
    ]

    operations = [
        migrations.RenameField(
            model_name='reminder',
            old_name='reminder_offset',
            new_name='offset',
        ),
        migrations.RenameField(
            model_name='reminder',
            old_name='reminder_unit',
            new_name='unit',
        ),
    ]
