# Generated by Django 5.1.1 on 2024-12-03 13:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_task'),
        ('interview', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='interviewtask',
            name='id',
        ),
        migrations.RemoveField(
            model_name='interviewtask',
            name='is_completed',
        ),
        migrations.RemoveField(
            model_name='interviewtask',
            name='name',
        ),
        migrations.AddField(
            model_name='interviewtask',
            name='task_ptr',
            field=models.OneToOneField(auto_created=True, default=1, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='core.task'),
            preserve_default=False,
        ),
    ]
