# Generated by Django 5.1.1 on 2024-12-10 15:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('interview', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='InterviewTask',
        ),
    ]
