# Generated by Django 5.1.1 on 2024-12-05 14:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_alert'),
        ('interview', '0002_remove_interviewtask_id_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='InterviewAlert',
            fields=[
                ('alert_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='core.alert')),
                ('interview', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='interview.interview')),
            ],
            bases=('core.alert',),
        ),
    ]
