# Generated by Django 5.1.1 on 2024-12-08 17:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('interview', '0003_interviewreminder'),
    ]

    operations = [
        migrations.AlterField(
            model_name='interviewreminder',
            name='interview',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reminders', to='interview.interview'),
        ),
    ]
