# Generated by Django 5.1.1 on 2024-12-03 16:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('interview', '0003_interviewalert'),
    ]

    operations = [
        migrations.AlterField(
            model_name='interviewalert',
            name='interview',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='alerts', to='interview.interview'),
        ),
    ]
