# Generated by Django 5.1.1 on 2024-12-04 16:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('interview', '0004_alter_interviewalert_interview'),
    ]

    operations = [
        migrations.AlterField(
            model_name='interviewalert',
            name='interview',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='interview.interview'),
        ),
    ]
