name: Build and Test
run-name: ${{ github.actor }} is pushing to ${{ github.ref }}

on: [push]

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11.9"
      - name: Upgrade pip
        run: python -m pip install --upgrade pip
      - name: Install dependencies
        run: pip install -r requirements.txt
      - name: Set PYTHONPATH
        run: echo "PYTHONPATH=$PYTHONPATH:$GITHUB_WORKSPACE/apptrack" >> $GITHUB_ENV
      - name: Set up settings.py
        run: |
          mkdir -p $GITHUB_WORKSPACE/apptrack/apptrack
          cat .github/workflows/settings.txt > $GITHUB_WORKSPACE/apptrack/apptrack/settings.py
          echo "SECRET_KEY = '${{ secrets.DJANGO_SECRET_KEY }}'" >> $GITHUB_WORKSPACE/apptrack/apptrack/settings.py
          echo "ANYMAIL = {'BREVO_API_KEY': '${{ secrets.BREVO_API_KEY }}', 'IGNORE_RECIPIENT_STATUS': True}" >> $GITHUB_WORKSPACE/apptrack/apptrack/settings.py
          echo "WEBPUSH_SETTINGS = {'VAPID_PUBLIC_KEY': ${{ secrets.VAPID_PUBLIC_KEY }},'VAPID_PRIVATE_KEY': ${{ secrets.VAPID_PRIVATE_KEY }}, 'VAPID_ADMIN_EMAIL': 'charlie.marshall1996@gmail.com'}" >> $GITHUB_WORKSPACE/apptrack/apptrack/settings.py
      - name: Apply migrations
        run: python apptrack/manage.py migrate

      - name: Test with pytest
        run: |
          pip install pytest pytest-cov
          pytest
      - name: Lint with Ruff
        run: |
          pip install ruff
          ruff check --output-format=github .
        continue-on-error: true

      - name: Upload pytest test results
        uses: actions/upload-artifact@v4
        with:
          name: pytest-results
          path: junit/test-results.xml
        if: ${{ always() }}

      - name: Cleanup settings.py
        if: always()
        run: rm -f $GITHUB_WORKSPACE/apptrack/apptrack/settings.py
