name: Continuous Integration
run-name: ${{ github.actor }} is pushing to ${{ github.ref }}

on: [push]

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11.9"
      - name: Upgrade pip
        run: python -m pip install --upgrade pip
      - name: Install dependencies
        run: pip install -r requirements.txt
      - name: Set PYTHONPATH
        run: echo "PYTHONPATH=$PYTHONPATH:/apptrack" >> $GITHUB_ENV
      - name: Test with pytest
        run: |
          pip install pytest pytest-cov
          pytest
      - name: Lint with Ruff
        run: |
          pip install ruff
          ruff check --output-format=github .
        continue-on-error: true
      - name: Upload pytest test results
        uses: actions/upload-artifact@v4
        with:
          name: pytest-results
          path: junit/test-results.xml
        if: ${{ always() }}

  deploy:
    runs-on: ubuntu-latest
    needs: build-and-test
    if: ${{ needs.build-and-test.result == 'success' }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Add SSH Key
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.PYANYWHERE_PRIVATE_KEY }}" > ~/.ssh/id_ed25519
          chmod 600 ~/.ssh/id_ed25519

      - name: Deploy to PythonAnywhere
        env:
          PYANYWHERE_USER: ${{ secrets.PYANYWHERE_USER }}
        run: |
          ssh -o StrictHostKeyChecking=no -i ~/.ssh/id_ed25519 "$PYANYWHERE_USER"@ssh.pythonanywhere.com << EOF
            cd ~/apptrack
            git pull origin main
          EOF
