name: Deploy Release
run-name: ${{ github.actor }} is deploying a release

on:
  - workflow_dispatch

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Find SSH Directory
        run: mkdir -p ~/.ssh
      - name: Add SSH Key
        run: echo "${{ secrets.PYANYWHERE_PRIVATE_KEY }}" > ~/.ssh/id_ed25519
      - name: Make SSH Key Readable
        run: chmod 600 ~/.ssh/id_ed25519
      - name: Pull latest changes
        run: |
          ssh -o StrictHostKeyChecking=no -i ~/.ssh/id_ed25519 "${{ secrets.PYANYWHERE_USER }}"@ssh.pythonanywhere.com << EOF
          cd apptrack
          git fetch origin
          git reset --hard origin/main
          EOF
      - name: Activate virtual environment and Install dependencies
        run: |
          ssh -o StrictHostKeyChecking=no -i ~/.ssh/id_ed25519 "${{ secrets.PYANYWHERE_USER }}"@ssh.pythonanywhere.com << EOF
          cd apptrack
          chmod +x ~/.virtualenvs/.venv/bin/activate
          source .virtualenvs/.venv/.bin/activate
          pip install -r requirements.txt
          EOF
