name: Deploy Release
run-name: ${{ github.actor }} is deploying a release

on:
  release:
    types:
      - published
      - edited

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Add SSH Key
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.PYANYWHERE_PRIVATE_KEY }}" > ~/.ssh/id_ed25519
          chmod 600 ~/.ssh/id_ed25519
          #test

      - name: Deploy to PythonAnywhere
        run: |
          ssh -o StrictHostKeyChecking=no -i ~/.ssh/id_ed25519 "${{ secrets.PYANYWHERE_USER }}"@ssh.pythonanywhere.com << EOF
          cd ~/apptrack
          git pull origin main --rebase --strategy-option ours
          cd apptrack
          python manage.py makemigrations
          python manage.py migrate
          EOF
